var config = {
  reticle:"https://yidaiyilu-s.oss-cn-shanghai.aliyuncs.com/reticle.glb",
  light:{
      defaultAmbientLight:"0.82",    
      defaultDirectionalLight:"2.5",
  },
  modelsInfo:[
      {
      model_idnex:0,
      glburl:"https://yidaiyilu-s.oss-cn-shanghai.aliyuncs.com/model/shenmiao_ganlanshu_hepingge.glb", 
      iconurl:"https://yidaiyilu-s.oss-cn-shanghai.aliyuncs.com/changebtn/1.png",
      size:5.01580
      }, 
      { 
      model_idnex:1,
      glburl:"https://yidaiyilu-s.oss-cn-shanghai.aliyuncs.com/model/baochuan.glb", 
      iconurl:"https://yidaiyilu-s.oss-cn-shanghai.aliyuncs.com/changebtn/2.png",
      size:6.50029
      }, 
      { 
      model_idnex:2,
      glburl:"https://yidaiyilu-s.oss-cn-shanghai.aliyuncs.com/model/chelizhi_huolieniao.glb", 
      iconurl:"https://yidaiyilu-s.oss-cn-shanghai.aliyuncs.com/changebtn/3.png",
      size:7.50704
      }, 
      { 
      model_idnex:3,
      glburl:"https://yidaiyilu-s.oss-cn-shanghai.aliyuncs.com/model/banma_feizhou.glb", 
      iconurl:"https://yidaiyilu-s.oss-cn-shanghai.aliyuncs.com/changebtn/4.png",
      size:33.54697
      }, 
      { 
      model_idnex:4,
      glburl:"https://yidaiyilu-s.oss-cn-shanghai.aliyuncs.com/model/shamo_luotuo.glb", 
      iconurl:"https://yidaiyilu-s.oss-cn-shanghai.aliyuncs.com/changebtn/5.png",
      size:6.82142
      }, 
      { 
      model_idnex:5,
      glburl:"https://yidaiyilu-s.oss-cn-shanghai.aliyuncs.com/model/tielu.glb", 
      iconurl:"https://yidaiyilu-s.oss-cn-shanghai.aliyuncs.com/changebtn/6.png",
      size:15.43312
      }
  ]
}

export function getInfoJson()
{
    const jsonstr = JSON.stringify(config);
    console.log(jsonstr);
}